{% set name = "opentelemetry-instrumentation-elasticsearch" %}
{% set version = "0.49b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_elasticsearch-{{ version }}.tar.gz
  sha256: 588e5f2b74f949f67d13586f6c88f43b7b0d200b3c84d4ff0c1e338882d53663

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.49b1
    - opentelemetry-semantic-conventions ==0.49b1
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - elasticsearch >=2.0
    # - elasticsearch >=6.0
    # - elasticsearch >=6.0
    # - elasticsearch >=6.0
    # - elasticsearch >=6.0
    # - elasticsearch >=6.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-elasticsearch
  summary: OpenTelemetry elasticsearch instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
