{% set name = "opentelemetry-instrumentation-elasticsearch" %}
{% set version = "0.49b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_elasticsearch-{{ version }}.tar.gz
  sha256: aaa2d1fd69055ec3144e7cf81a096d004ab6fd6e782da80b0aea1b0ad1da4df2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.49b0
    - opentelemetry-semantic-conventions ==0.49b0
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-elasticsearch 
    # - elasticsearch-dsl >=2.0
    # - elasticsearch >=2.0
    # - elasticsearch >=2.0
    # - elasticsearch >=6.0
    # - elasticsearch >=6.0
    # - elasticsearch >=6.0
    # - elasticsearch >=6.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-elasticsearch
  summary: OpenTelemetry elasticsearch instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
